@startuml

skinparam style strictuml

title Google OAuth Devices Sequence

control "Limited-Device" as ld
control "Google-OAuth-Server" as gos
control "Rich Device" as rd 
actor User as u

ld -> gos : request code(client_id, scope)
gos -> ld : [device_code, expires_in, interval, user_code, verification_url]

====

ld -> ld : display(user_code)
ld -> rd : open login(verification_url)

u -> rd : log into google account
u -> rd : enter(user_code)
u -> rd : allow scope

====

ld -> gos : poll(client_id, client_secret, device_code, grant_type)
gos -> ld : [access_token, expires_in, refresh_token, scope, token_type]
ld -> ld : remember(refresh_token)

ld -> gos : call api (token_type, access_token, api-url)

====

ld -> gos : refresh(client_id, client_secret, grant_type, refresh_token)
gos -> ld : [access_token, expires_in, scope, token_type]

@enduml